Repository BlueMedoraPublic/bpcli, pull requests merged in 2019-07, with the labels that each got.

#1 Travis
  .travis.yml
Labels: continuous integration

#9 add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#15 skip credential id uuid check, if the length of credential is zero. T…
  bindplane/sdk/source.go
  bindplane/sdk/source_test.go
Labels: bug

#17 Tutorial
  README.md
  doc/google-cloud-tutorial/bpcli-intro.md
Labels: enhancement
